services:
  # Main application
  fpt-agent:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: fpt-agent
    environment:
      - OPENAI_BASE_URL=https://api.iunhi.com
      - OPENAI_API_KEY=sk-dummy-key
      - REDIS_URL=redis://redis:6379/0
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333

  # Redis cache
  redis:
    image: redis:7-alpine
    container_name: fpt-agent-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Qdrant vector database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: fpt-agent-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Development service
  fpt-agent-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: fpt-agent-dev
    environment:
      - FPT_AGENT_ENVIRONMENT=development
      - FPT_AGENT_LOG_LEVEL=DEBUG
      - FPT_AGENT_CACHE_BACKEND=memory
      - FPT_AGENT_VECTOR_BACKEND=memory
    volumes:
      - .:/app
      - ./logs:/app/logs
    ports:
      - "8001:8000"
    command: python full_demo.py
    profiles:
      - dev

volumes:
  redis_data:
    driver: local
  qdrant_data:
    driver: local

networks:
  default:
    name: fpt-agent-network
