services:
  # Main application
  fpt-agent:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: fpt-agent
    environment:
      - OPENAI_BASE_URL=https://api.iunhi.com
      - OPENAI_API_KEY=sk-dummy-key
      - DATABASE_URL=postgresql+psycopg://ai:ai@postgres:5432/ai
      - REDIS_URL=redis://redis:6379/0
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_API_KEY=your_qdrant_api_key_here
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - qdrant

  # Redis cache
  redis:
    image: redis:7-alpine
    container_name: fpt-agent-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL with PgVector
  postgres:
    image: pgvector/pgvector:pg17
    container_name: fpt-agent-postgres
    ports:
      - "5532:5432"
    environment:
      - POSTGRES_DB=ai
      - POSTGRES_USER=ai
      - POSTGRES_PASSWORD=ai
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai -d ai"]
      interval: 30s
      timeout: 10s
      retries: 3
  # Qdrant vector database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: fpt-agent-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
  qdrant_data:
    driver: local

networks:
  default:
    name: fpt-agent-network
